name: DiscordBridge
version: 1.0
main: com.asriel.discordbridge.DiscordBridgePlugin
api-version: 1.20
author: Asriel

commands:
  getmap:
    description: 領取指定地圖
    usage: /getmap [map0|map1|map2...]
  bind:
    description: 綁定網頁帳號
    usage: /bind <token>
  check:
    description: 查看綁定帳號資訊
    usage: /check
  claim:
    description: 領取簽到獎勵
    usage: /claim